/**
 * Noms français des marqueurs (toutes les sortes nommées par les cartes du Standard) ; une sorte inconnue garde son nom
 * anglais. Lus par l'interface (pastilles) et par les questions du moteur (« quel marqueur retirer ? »).
 */
export const COUNTER_LABELS: Readonly<Record<string, string>> = {
  stun: "Étourdi",
  loyalty: "Loyauté",
  lore: "Histoire",
  finality: "Finalité",
  charge: "Charge",
  time: "Temps",
  plan: "Plan",
  quest: "Quête",
  flying: "Vol",
  first: "Initiative",
  "first strike": "Initiative",
  "double strike": "Double initiative",
  indestructible: "Indestructible",
  lifelink: "Lien de vie",
  deathtouch: "Contact mortel",
  trample: "Piétinement",
  hexproof: "Défense talismanique",
  reach: "Portée",
  haste: "Célérité",
  menace: "Menace",
  vigilance: "Vigilance",
  page: "Page",
  dread: "Effroi",
  stash: "Butin",
  blight: "Flétrissure",
  fire: "Feu",
  hone: "Affûtage",
  net: "Filet",
  bore: "Forage",
  landmark: "Repère",
  revival: "Résurrection",
  divinity: "Divinité",
  flood: "Crue",
  strike: "Frappe",
  shield: "Bouclier",
  incubation: "Incubation",
  fellowship: "Camaraderie",
  bait: "Appât",
  soul: "Âme",
  wish: "Souhait",
  loot: "Pillage",
  coin: "Pièce",
  supply: "Provision",
  skewer: "Embrochement",
  growth: "Croissance",
  dream: "Rêve",
  conqueror: "Conquérant",
  ingenuity: "Ingéniosité",
  film: "Pellicule",
  invasion: "Invasion",
  impostor: "Imposteur",
  bloodstain: "Tache de sang",
  unlock: "Déverrouillage",
  rev: "Régime",
  chorus: "Chœur",
  point: "Point",
  decayed: "Décomposition",
  possession: "Possession",
  nest: "Nid",
  oil: "Huile",
  shell: "Carapace",
  speed: "Vitesse",
};

/** Nom français d'une sorte de marqueur (« +1/+1 » et les sortes inconnues : telles quelles). */
export const counterLabel = (kind: string): string => COUNTER_LABELS[kind] ?? kind;
