import { msg } from "./text";

/**
 * Names of the counters as the cards write them (a "lore" counter), English texts translated by the catalogs (the
 * French names are those of the French card text); the keys are the kinds of the engine
 * (`firstStrike`, not "first strike"). Every kind put or read by a script has one (`cards/test/ability-flags.test.ts`);
 * an unknown kind keeps its raw name. Read by the interface (badges) and by the questions of the engine ("which counter
 * to remove?").
 */
export const COUNTER_LABELS: Readonly<Record<string, string>> = {
  stun: msg("Stun"),
  loyalty: msg("Loyalty"),
  lore: msg("Lore"),
  finality: msg("Finality"),
  charge: msg("Charge"),
  time: msg("Time"),
  plan: msg("Plan"),
  quest: msg("Quest"),
  flying: msg("Flying"),
  firstStrike: msg("First strike"),
  doubleStrike: msg("Double strike"),
  indestructible: msg("Indestructible"),
  lifelink: msg("Lifelink"),
  deathtouch: msg("Deathtouch"),
  trample: msg("Trample"),
  hexproof: msg("Hexproof"),
  reach: msg("Reach"),
  haste: msg("Haste"),
  menace: msg("Menace"),
  vigilance: msg("Vigilance"),
  page: msg("Page"),
  dread: msg("Dread"),
  stash: msg("Stash"),
  blight: msg("Blight"),
  fire: msg("Fire"),
  hone: msg("Hone"),
  net: msg("Net"),
  bore: msg("Bore"),
  landmark: msg("Landmark"),
  revival: msg("Revival"),
  divinity: msg("Divinity"),
  flood: msg("Flood"),
  shield: msg("Shield"),
  incubation: msg("Incubation"),
  fellowship: msg("Fellowship"),
  bait: msg("Bait"),
  soul: msg("Soul"),
  wish: msg("Wish"),
  loot: msg("Loot"),
  coin: msg("Coin"),
  supply: msg("Supply"),
  skewer: msg("Skewer"),
  growth: msg("Growth"),
  dream: msg("Dream"),
  conqueror: msg("Conqueror"),
  ingenuity: msg("Ingenuity"),
  film: msg("Film"),
  invasion: msg("Invasion"),
  impostor: msg("Impostor"),
  bloodstain: msg("Bloodstain"),
  unlock: msg("Unlock"),
  rev: msg("Rev"),
  chorus: msg("Chorus"),
  point: msg("Point"),
  decayed: msg("Decayed"),
  possession: msg("Possession"),
  nest: msg("Nest"),
  oil: msg("Oil"),
  shell: msg("Shell"),
  speed: msg("Speed"),
  tower: msg("Tower"),
  luck: msg("Luck"),
  rad: msg("Rad"),
  descent: msg("Descent"),
  bloodline: msg("Bloodline"),
  pressure: msg("Pressure"),
  age: msg("Age"),
  vow: msg("Vow"),
  story: msg("Story"),
  burden: msg("Burden"),
  // Not a printed counter: the engine records monstrosity this way (701.37, Grim Giganotosaurus).
  monstrous: msg("Monstrous"),
};

/** Name of a kind of counter ("+1/+1" and the unknown kinds: as they are). */
export const counterLabel = (kind: string): string => COUNTER_LABELS[kind] ?? kind;
