/**
 * Noms français des marqueurs, tels que les écrit le texte français des cartes (marqueur « sapience ») ; les clés sont
 * les sortes du moteur (`firstStrike`, pas « first strike »). Toute sorte posée ou lue par un script en a un
 * (`cards/test/ability-flags.test.ts`) ; une sorte inconnue garde son nom anglais. Lus par l'interface (pastilles) et
 * par les questions du moteur (« quel marqueur retirer ? »).
 */
export const COUNTER_LABELS: Readonly<Record<string, string>> = {
  stun: "Étourdissement",
  loyalty: "Loyauté",
  lore: "Sapience",
  finality: "Fatalité",
  charge: "Charge",
  time: "Temps",
  plan: "Manigance",
  quest: "Quête",
  flying: "Vol",
  firstStrike: "Initiative",
  doubleStrike: "Double initiative",
  indestructible: "Indestructible",
  lifelink: "Lien de vie",
  deathtouch: "Contact mortel",
  trample: "Piétinement",
  hexproof: "Défense talismanique",
  reach: "Portée",
  haste: "Célérité",
  menace: "Menace",
  vigilance: "Vigilance",
  page: "Page",
  dread: "Effroi",
  stash: "Réserve",
  blight: "Gangrène",
  fire: "Feu",
  hone: "Perfectionnement",
  net: "Filet",
  bore: "Forage",
  landmark: "Repère",
  revival: "Renaissance",
  divinity: "Divinité",
  flood: "Inondation",
  shield: "Bouclier",
  incubation: "Incubation",
  fellowship: "Communauté",
  bait: "Appât",
  soul: "Âme",
  wish: "Souhait",
  loot: "Butin",
  coin: "Pièce",
  supply: "Provision",
  skewer: "Broche",
  growth: "Croissance",
  dream: "Rêve",
  conqueror: "Conquérant",
  ingenuity: "Ingéniosité",
  film: "Pellicule",
  invasion: "Invasion",
  impostor: "Imposteur",
  bloodstain: "Tache de sang",
  unlock: "Déverrouillage",
  rev: "Rotation",
  chorus: "Chœur",
  point: "Point",
  decayed: "Décomposition",
  possession: "Possession",
  nest: "Nid",
  oil: "Huile",
  shell: "Carapace",
  speed: "Vitesse",
  tower: "Tour",
  luck: "Chance",
  rad: "Radiation",
  descent: "Descente",
  bloodline: "Lignée",
  pressure: "Pression",
  age: "Âge",
  vow: "Serment",
  story: "Histoire",
  burden: "Fardeau",
  // Pas un marqueur imprimé : le moteur note ainsi la monstruosité (701.37, Grim Giganotosaurus).
  monstrous: "Monstrueux",
};

/** Nom français d'une sorte de marqueur (« +1/+1 » et les sortes inconnues : telles quelles). */
export const counterLabel = (kind: string): string => COUNTER_LABELS[kind] ?? kind;
