export { type AutopilotSettings, autopilotDecision, autoTarget, DEFAULT_AUTOPILOT } from "./autopilot";
export type { CardScript } from "./dsl";
export * as dsl from "./dsl";
export { createGame, type GameOptions, type PlayerSetup, type StepResult, submit } from "./game";
export { type Agent, fallbackDecision, GameHost, type HostOptions } from "./host";
export { legalActions, meaningfulActions } from "./legal";
export { availableMana, costToText, manaSources, manaValue, parseManaCost, solvePayment } from "./mana";
export { isPermanentCard, modesOf, RulesError } from "./stack";
export { type Characteristics, chars, creaturesControlledBy, hasKeyword, isCreature, isSummoningSick, opponentOf } from "./state";
export { isLegalTarget, legalTargets } from "./targets";
export { attackCandidates, blockCandidates, canAttack, canBlock, MAX_HAND_SIZE } from "./turn";
export * from "./types";
export type { CardFace, GameView, ObjectView, PendingView, PlayerView, StackItemView } from "./view";
export { cardFace, filterEvents, objectView, projectView } from "./view";
